### PR TITLE
fix: support nullable primary key columns

### LINKED ISSUE #83: Primary Key column has always NOT NULL after using update command
### Descripton:
Primary Key column is always not nullable after using update command but according to documentation on Cloud Spanner:
https://cloud.google.com/spanner/docs/schema-and-data-model#notes_about_key_columns
Primary Key columns can be defined to store NULLs.

### Steps to reproduce:

Use changeLog as below:
```
databaseChangeLog:
- changeSet:
    id: 1617793276323-1
    author: author
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              primaryKey: true
              primaryKeyName: PRIMARY_KEY
            name: FIRST_1
            type: STRING(1024)
        - column:
            constraints:
              nullable: false
              primaryKey: true
              primaryKeyName: PRIMARY_KEY
            name: FIRST_2
            type: STRING(MAX)
        - column:
            constraints:
              primaryKey: true
              primaryKeyName: PRIMARY_KEY
            name: FIRST_3
            type: INT64
        - column:
            name: FIRST_4
            type: INT64
        tableName: FIRST_TABLE
```

In command:
liquibase --url="jdbc:cloudspanner:/projects/\<project_name\>/instances/\<instance_name\>/databases/\<db_name\>" --changeLogFile=changeLog.yml update

After that in schema you can see all Primary Keys as a not nullable but should be only FIRST_2 column.
Even adding "nullable: true" does not help.

### PR DESCRIPTION
**Pull request by olavloite**
Liquibase automatically adds a NotNullConstraint to all primary key columns, regardless whether these have been marked as nullable or not. Cloud Spanner supports nullable primary key columns. This change adds a custom CreateTable change and statement for Spanner that removes the automatically generated NotNullConstraint from primary key columns.

NotNullConstraints that are explicitly set on primary key columns are respected.

Fixes #83

### CODE REVIEW

File: src/main/java/liquibase/ext/spanner/sqlgenerator/CreateTableStatementSpanner.java [hunk 1]
```diff
@@ -0,0 +1,64 @@
...
+    if (!containsNotNullConstraintForColumn(columnName, constraints)) {
+      getNotNullColumns().remove(columnName);
+    }
+    return statement;
+  }
+  
+  @Override
+  public CreateTableStatement addPrimaryKeyColumn(String columnName, LiquibaseDataType columnType, Object defaultValue,
+      Boolean validate,String keyName, String tablespace, ColumnConstraint... constraints) {
+    CreateTableStatement statement = super.addPrimaryKeyColumn(columnName, columnType, defaultValue, keyName, tablespace, constraints);
```
Comment (mescanne) [inline src/main/java/liquibase/ext/spanner/sqlgenerator/CreateTableStatementSpanner.java:46]: This addPrimaryKeyColumn doesn't use the method with validate. Shouldn't it be aligned? (Not sure the difference in methods!)

File: src/test/resources/create-table-with-all-liquibase-types.spanner.yaml [hunk 2]
```diff
@@ -31,6 +31,7 @@ databaseChangeLog:
                 type:    BIGINT
                 constraints:
                   primaryKey: true
+                  nullable: false
```
Comment (mescanne) [inline src/test/resources/create-table-with-all-liquibase-types.spanner.yaml:34]: Do we still have a test that has primaryKey with nullable: true? Just to ensure that containsNotNullConstraintForColumn etc are all working correctly.

File: src/main/java/liquibase/ext/spanner/sqlgenerator/CreateTableStatementSpanner.java (hunk 1 above)
Comment (olavloite) [reply src/main/java/liquibase/ext/spanner/sqlgenerator/CreateTableStatementSpanner.java:46]: Good catch, they should certainly be aligned.

File: src/test/resources/create-table-with-all-liquibase-types.spanner.yaml (hunk 2 above)
Comment (olavloite) [reply src/test/resources/create-table-with-all-liquibase-types.spanner.yaml:34]: Yes, there are a number of them, as every test that does not specify anything will by default be `nullable: true`. But just to be 100% sure I've added the `nullable: true` explicitly to one of the tests as well.

**Review by mescanne — APPROVED** [review]
Looks good.
